spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gerenciamento_livros?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
