#spring.jpa.open-in-view=false

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console
